version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    volumes:
       - .:/usr/share/nginx/html
    ports:
      - 80:80

  #Because nginx references vue3_ui we have to specify it in the container_name
  vue3_ui:
    image: "vue3_ui"
    ports:
      - "8080:8080"
    build:
      context: ./vue3_ui
    container_name: vue3_ui
    volumes:
      - ./:/home/node/vueapp

  react_ui:
    image: "react_ui"
    ports:
      - "8081:8080"
    container_name: react_ui
    build:
      context: ./react_ui
    volumes:
      - ./:/home/node/reactapp

  static_ui:
    image: "static_ui"
    container_name: static_ui
    build:
      context: ./static_ui
    volumes:
      - ./:/home/node/staticapp
      




      
