version: "3.8"

services:
  node_16_api:
    image: "node_16_api"
    ports:
      - "3000:3000"
    build:
      context: ./node_16_api

  node_17_typescript_api:
    image: "node_17_typescript_api"
    ports:
      - "3001:3000"
    build:
      context: ./node_17_api_typescript

  go_lang_api:
    image: "go_lang_api"
    ports:
      - "3002:8080"
    build:
      context: ./golang_api

  python_api:
    image: "python_api"
    ports:
      - "3003:5000"
    build:
      context: ./python_api
    volumes:
      - ./:/home/node/python_api





      
